global using CsabaDu.DynamicDataTests_NetConf2024.SampleTypes;
global using CsabaDu.DynamicDataTests_NetConf2024.TestMembers.DynamicDataSources;
global using CsabaDu.DynamicDataTests_NetConf2024.TestMembers.GeneralTestMembers;
global using System.Reflection;
